// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BundlerMinifierVsix
{
				static class Vsix
				{
								public const string Id = "7973f4ce-6596-4b28-8407-2e64ecfbc707";
								public const string Name = "Bundler & Minifier (OUT)";
								public const string Description = "Adds support for bundling and minifying JavaScript, CSS and HTML files in any project.";
								public const string Language = "en-US";
								public const string Version = "3.3.101";
								public const string Author = "Mads Kristensen";
								public const string Tags = "bundle, bundling, minify, minification, js, css, html";
				}
}
